<a href="https://colab.research.google.com/github/dm-fedorov/pandas_basic/blob/master/упражнения/Анализ_трафика.ipynb"><img align="left" src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open in Colab" title="Open and Execute in Google Colaboratory" target="_blank"></a>

In [4]:
import pandas as pd
import numpy as np

In [14]:
df = pd.read_csv("https://raw.githubusercontent.com/dm-fedorov/pandas_basic/master/%D1%83%D0%BF%D1%80%D0%B0%D0%B6%D0%BD%D0%B5%D0%BD%D0%B8%D1%8F/data/syn_scan_24112020.csv")
df.head()

,time,source,destination,protocol,length,tcp_retransmission,srcport,dstport,flags,seq_ack,win,len,mss,10
0,0.000000,172.16.0.8,64.13.134.52,TCP,58,False,36050,443,[SYN],Seq=0,Win=3072,Len=0,MSS=1460,NaN
1,0.001539,172.16.0.8,64.13.134.52,TCP,58,False,36050,143,[SYN],Seq=0,Win=3072,Len=0,MSS=1460,NaN
2,0.001597,172.16.0.8,64.13.134.52,TCP,58,False,36050,3306,[SYN],Seq=0,Win=2048,Len=0,MSS=1460,NaN
3,0.001650,172.16.0.8,64.13.134.52,TCP,58,False,36050,199,[SYN],Seq=0,Win=3072,Len=0,MSS=1460,NaN
4,0.001703,172.16.0.8,64.13.134.52,TCP,58,False,36050,111,[SYN],Seq=0,Win=1024,Len=0,MSS=1460,NaN

In [15]:
df["time"] = pd.to_datetime(df["time"])
df.set_index(df["time"])

,time,source,destination,protocol,length,tcp_retransmission,srcport,dstport,flags,seq_ack,win,len,mss,10
time,,,,,,,,,,,,,,
1970-01-01 00:00:00.000000000,1970-01-01 00:00:00.000000000,172.16.0.8,64.13.134.52,TCP,58,False,36050,443,[SYN],Seq=0,Win=3072,Len=0,MSS=1460,NaN
1970-01-01 00:00:00.000000000,1970-01-01 00:00:00.000000000,172.16.0.8,64.13.134.52,TCP,58,False,36050,143,[SYN],Seq=0,Win=3072,Len=0,MSS=1460,NaN
1970-01-01 00:00:00.000000000,1970-01-01 00:00:00.000000000,172.16.0.8,64.13.134.52,TCP,58,False,36050,3306,[SYN],Seq=0,Win=2048,Len=0,MSS=1460,NaN
1970-01-01 00:00:00.000000000,1970-01-01 00:00:00.000000000,172.16.0.8,64.13.134.52,TCP,58,False,36050,199,[SYN],Seq=0,Win=3072,Len=0,MSS=1460,NaN
1970-01-01 00:00:00.000000000,1970-01-01 00:00:00.000000000,172.16.0.8,64.13.134.52,TCP,58,False,36050,111,[SYN],Seq=0,Win=1024,Len=0,MSS=1460,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1970-01-01 00:00:00.000000009,1970-01-01 00:00:00.000000009,64.13.134.52,172.16.0.8,TCP,60,True,80,36050,"[SYN,ACK]",Seq=0Ack=1,Win=5840,Len=0,MSS=1380,NaN
1970-01-01 00:00:00.000000011,1970-01-01 00:00:00.000000011,64.13.134.52,172.16.0.8,TCP,60,True,22,36050,"[SYN,ACK]",Seq=0Ack=1,Win=5840,Len=0,MSS=1380,NaN
1970-01-01 00:00:00.000000021,1970-01-01 00:00:00.000000021,64.13.134.52,172.16.0.8,TCP,60,True,53,36050,"[SYN,ACK]",Seq=0Ack=1,Win=5840,Len=0,MSS=1380,NaN
1970-01-01 00:00:00.000000021,1970-01-01 00:00:00.000000021,64.13.134.52,172.16.0.8,TCP,60,True,80,36050,"[SYN,ACK]",Seq=0Ack=1,Win=5840,Len=0,MSS=1380,NaN
1970-01-01 00:00:00.000000023,1970-01-01 00:00:00.000000023,64.13.134.52,172.16.0.8,TCP,60,True,22,36050,"[SYN,ACK]",Seq=0Ack=1,Win=5840,Len=0,MSS=1380,NaN

In [18]:
df.head()

,time,source,destination,protocol,length,tcp_retransmission,srcport,dstport,flags,seq_ack,win,len,mss,10
0,1970-01-01,172.16.0.8,64.13.134.52,TCP,58,False,36050,443,[SYN],Seq=0,Win=3072,Len=0,MSS=1460,NaN
1,1970-01-01,172.16.0.8,64.13.134.52,TCP,58,False,36050,143,[SYN],Seq=0,Win=3072,Len=0,MSS=1460,NaN
2,1970-01-01,172.16.0.8,64.13.134.52,TCP,58,False,36050,3306,[SYN],Seq=0,Win=2048,Len=0,MSS=1460,NaN
3,1970-01-01,172.16.0.8,64.13.134.52,TCP,58,False,36050,199,[SYN],Seq=0,Win=3072,Len=0,MSS=1460,NaN
4,1970-01-01,172.16.0.8,64.13.134.52,TCP,58,False,36050,111,[SYN],Seq=0,Win=1024,Len=0,MSS=1460,NaN

# Задание

1. Определите все уникальные протоколы, которые встречаются в сетевом трафике:

2. Определите все уникальные сетевые порты, которые встречаются в сетевом трафике:

3. Определите количественное распределение сетевых портов в сетевом трафике (постройте график вида гистограмма):

4. Определите IP-адреса и сетевые порты, для которых установлен флаг tcp_retransmission:

5. Определите все уникальные IP-адреса источника и назначения в сетевом  трафике: